version: "3.7"

services:
    redis-stack:
        image: redis/redis-stack:7.2.0-v6
        container_name:  redis-stack
        restart: always

        #  mount the volumes so we can change code and hot reload
        volumes:
            - "./redis-stack.conf:/redis-stack.conf"
            - "./data:/data"

        #  port allows the host machine to link to container
        ports:
            - "10001:6379"
            - "13333:8001"

        environment:
            - REDIS_ARGS="--requirepass mypassword"
